apiVersion: v1
kind: Service
metadata:
  labels:
    nfsserver/component: nfs-server
  name: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    role: nfs-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    nfsserver/component: nfs-server
    role: nfs-server
  name: nfs-server
spec:
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - image: k8s.gcr.io/volume-nfs:0.8
        name: nfs-server
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 20048
          name: mountd
        - containerPort: 111
          name: rpcbind
        securityContext:
          privileged: true
