apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    nfsvolume/component: nfs-volume
  name: nfs1
  namespace: anonymous
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /
    server: nfs-cluster-ip
